### ISSUE TITLE
采用repnr_restormer在finetune时报错

### ISSUE THREAD

**Issue by yuanchen-wang** [Srameo/LED#28]
采用repnr_restormer在finetune时报错，log如下：

INFO: End of training. Time consumed: 0:05:02
INFO: Save the latest model.
Traceback (most recent call last):
  File "led/train.py", line 223, in <module>
    train_pipeline(root_path)
  File "led/train.py", line 212, in train_pipeline
    model.save(epoch=-1, current_iter=-1)  # -1 stands for the latest
  File "raw_image_denoising_model.py", line 367, in save
    self.save_network([self.net_g, self.net_g.deploy()], 'net_g', current_iter, param_key=['params', 'params_deploy'])
  File "anaconda3/envs/pytorch-1.13/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "led/archs/repnr_utils.py", line 346, in deploy
    deploy(self.base_module, self.repnr_module)
  File "led/archs/repnr_utils.py", line 343, in deploy
    deploy(mm, getattr(m, n))
  File "led/archs/repnr_utils.py", line 343, in deploy
    deploy(mm, getattr(m, n))
  File "led/archs/repnr_utils.py", line 336, in deploy
    m_bak.bias.data = bias
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by Srameo** [comment]
Thanks to [natsunoshion](https://github.com/natsunoshion)! Please refer to https://github.com/Srameo/LED/pull/33.
